import { JobResult } from '../../queue/types';

/**
 * Format summary message
 */
export function formatSummaryMessage(summary: string, chapters: any[] = []): string {
  let message = `📝 **Video Summary**\n\n${summary}`;

  if (chapters.length > 0) {
    message += `\n\n**Key Topics:**\n`;
    chapters.forEach(chapter => {
      message += `• ${chapter.title}\n`;
    });
  }

  return message;
}

/**
 * Format chapters message
 */
export function formatChaptersMessage(chapters: any[]): string {
  let message = `🎬 **Video Chapters**\n\n`;

  chapters.forEach((chapter, index) => {
    // Calculate duration if needed, or just use start/end
    message += `*${index + 1}. ${chapter.title}* (${chapter.start_time} - ${chapter.end_time})\n` +
    `${chapter.summary}\n\n`;
  });

  return message;
}

/**
 * Format job result into a Telegram message (Combined)
 */
export function formatJobResult(result: JobResult): string {
  if (!result.success) {
    return `❌ **Error Processing Video**\n\n${result.error || 'Unknown error occurred.'}`;
  }

  const parts: string[] = [];

  // Add summary if available
  if (result.summary) {
    parts.push(`📝 **Summary**\n\n${result.summary}`);
  }

  // Add chapters if available
  if (result.chapters && result.chapters.length > 0) {
    parts.push(`🎬 **Chapters**`);

    result.chapters.forEach((chapter, index) => {
      parts.push(
        `*${index + 1}. ${chapter.title}* (${chapter.start_time} - ${chapter.end_time})\n` +
        `${chapter.summary}\n`
      );
    });
  }

  // Add footer
  parts.push(`\n_Generated by Clean Class Recorder_ 🤖`);

  return parts.join('\n\n');
}

/**
 * Calculate duration between two timestamps (HH:MM:SS)
 */
function calculateDuration(start: string, end: string): string {
  // parsing "HH:MM:SS" or "MM:SS"
  const parseSeconds = (timeStr: string) => {
    const parts = timeStr.split(':').map(Number);
    if (parts.length === 3) return parts[0] * 3600 + parts[1] * 60 + parts[2];
    if (parts.length === 2) return parts[0] * 60 + parts[1];
    return 0;
  };

  const diff = parseSeconds(end) - parseSeconds(start);
  if (diff < 0) return '';

  const minutes = Math.floor(diff / 60);
  const seconds = diff % 60;

  return `${minutes}m ${seconds}s`;
}

/**
 * Format progress message
 */
export function formatProgressMessage(stage: string, progress: number, message: string): string {
  const progressBarLength = 10;
  const filledLength = Math.round((progressBarLength * progress) / 100);
  const emptyLength = progressBarLength - filledLength;

  const progressBar = '▓'.repeat(filledLength) + '░'.repeat(emptyLength);

  return `Processing Video...\n\n` +
         `${progressBar} ${progress}%\n\n` +
         `Status: ${message}\n` +
         `Stage: ${stage}`;
}
